//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contacts
    {
        public int ContactID { get; set; }

        [Required(ErrorMessage = "vaaditaan!")]
        public int ContractorID { get; set; }

        public Nullable<int> PersonID { get; set; }

        public string PhoneNumber { get; set; }

        public string Email { get; set; }

    
        public virtual Contractors Contractors { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
