//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForMonthlySpendingsCharts
    {
        public long rowId { get; set; }
        public string MonthYearDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SpendingTypeID { get; set; }
    }
}
