//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForOtherSpendingTypeCharts
    {
        public Nullable<long> rowid { get; set; }
        public System.DateTime DateBegin { get; set; }
        public Nullable<decimal> DailySpendings { get; set; }
        public int OtherSpendingTypeId { get; set; }
    }
}
