//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyAndOtherSpendingsByMonth
    {
        public Nullable<long> Rivi { get; set; }
        public Nullable<int> Vuosi { get; set; }
        public decimal Tammikuu { get; set; }
        public decimal Helmikuu { get; set; }
        public decimal Maaliskuu { get; set; }
        public decimal Huhtikuu { get; set; }
        public decimal Toukokuu { get; set; }
        public decimal Kesäkuu { get; set; }
        public decimal Heinäkuu { get; set; }
        public decimal Elokuu { get; set; }
        public decimal Syyskuu { get; set; }
        public decimal Lokakuu { get; set; }
        public decimal Marraskuu { get; set; }
        public decimal Joulukuu { get; set; }
    }
}
