//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySummary
    {
        public Nullable<long> Rivi { get; set; }
        public Nullable<int> MonthOfSpending { get; set; }
        public Nullable<int> YearOfSpending { get; set; }
        public decimal Kokonaishinta { get; set; }
        public string TypeName { get; set; }
    }
}
