//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherSpendings
    {
        public int OtherSpendingsID { get; set; }
        public System.DateTime DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Description { get; set; }
        public int OtherSpendingTypeID { get; set; }
        public Nullable<int> ContractorID { get; set; }
        public decimal Price { get; set; }
        public int LoginID { get; set; }
    
        public virtual Contractors Contractors { get; set; }
        public virtual Logins Logins { get; set; }
        public virtual OtherSpendingTypes OtherSpendingTypes { get; set; }
    }
}
